export const selectAnimalsList = (state) => state.animals.animalsList
export const selectPerPage = (state) => state.animals.animalsPerPage
export const selectTotal = (state) => state.animals.total
export const selectBreeds = (state) => state.animals.breedsList
export const selectTypes = (state) => state.animals.typesList
export const selectInoc = (state) => state.animals.inocList
export const selectDiseases = (state) => state.animals.diseasesList
export const selectLogined = (state) => state.animals.logined
export const selectFavour = (state) => state.animals.favouritesList
